# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: virtru.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("virtru.proto", :syntax => :proto3) do
    add_message "virtru.EncryptRequest" do
      optional :unprotectedString, :string, 1
    end
    add_message "virtru.EncryptReply" do
      optional :protectedString, :string, 1
    end
    add_message "virtru.DecryptRequest" do
      optional :protectedString, :string, 1
    end
    add_message "virtru.DecryptReply" do
      optional :unprotectedString, :string, 1
    end
  end
end

module Virtru
  EncryptRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("virtru.EncryptRequest").msgclass
  EncryptReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("virtru.EncryptReply").msgclass
  DecryptRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("virtru.DecryptRequest").msgclass
  DecryptReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("virtru.DecryptReply").msgclass
end
