# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: virtru.proto for package 'virtru'

require 'grpc'
require 'virtru_pb'

module Virtru
  module Virtru
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'virtru.Virtru'

      rpc :Decrypt, ::Virtru::DecryptRequest, ::Virtru::DecryptReply
      rpc :Encrypt, ::Virtru::EncryptRequest, ::Virtru::EncryptReply
    end

    Stub = Service.rpc_stub_class
  end
end
